"""empty message

Revision ID: 0da56ff9e390
Revises: 9df15334a84c
Create Date: 2018-12-12 12:09:55.962296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da56ff9e390'
down_revision = '9df15334a84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_content',
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_content')
    # ### end Alembic commands ###
