"""empty message

Revision ID: 30244db6759e
Revises: b6b5e20b072d
Create Date: 2018-12-20 14:04:53.538508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30244db6759e'
down_revision = 'b6b5e20b072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brownfield_site_register', sa.Column('validation_updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brownfield_site_register', 'validation_updated_date')
    # ### end Alembic commands ###
