"""empty message

Revision ID: 31c6eb005764
Revises: 8e6a2d9992c7
Create Date: 2018-09-25 12:35:39.698621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31c6eb005764'
down_revision = '8e6a2d9992c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature', 'geojson')
     # ### end Alembic commands ###
