"""empty message

Revision ID: 3ae1bcd3f731
Revises: e2be4d7534ce
Create Date: 2018-11-27 16:08:26.141659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ae1bcd3f731'
down_revision = 'e2be4d7534ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brownfield_site_validation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brownfield_site_validation',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('organisation_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.organisation'], name='brownfield_site_validation_organisation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='brownfield_site_validation_pkey')
    )
    # ### end Alembic commands ###
