"""empty message

Revision ID: 4bd471ac67bb
Revises: 
Create Date: 2018-07-25 15:11:56.922965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bd471ac67bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brownfield_site_publication',
    sa.Column('publication', sa.String(length=64), nullable=False),
    sa.Column('organisation', sa.String(length=64), nullable=True),
    sa.Column('data_url', sa.Text(), nullable=True),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('publication')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brownfield_site_publication')
    # ### end Alembic commands ###
