"""empty message

Revision ID: 70a3c7402419
Revises: 
Create Date: 2018-10-24 16:10:41.781421

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70a3c7402419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
        sa.Column('organisation', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=True),
        sa.Column('website', sa.String(length=256), nullable=True),
        sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326), nullable=True),
        sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('brownfield_register_publication', sa.String(length=64), nullable=True),
        sa.Column('brownfield_register_url', sa.Text(), nullable=True),
        sa.Column('brownfield_register_copyright', sa.String(length=64), nullable=True),
        sa.Column('brownfield_register_licence', sa.String(length=64), nullable=True),
        sa.Column('brownfield_register_suffix', sa.String(length=64), nullable=True),
        sa.Column('brownfield_register_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('organisation')
    )
    op.create_table('brownfield_site_validation',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('data_source', sa.Text(), nullable=True),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('organisation_id', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['organisation_id'], ['organisation.organisation'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brownfield_site_validation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
