"""empty message

Revision ID: 87ff1e76501f
Revises: 31c6eb005764
Create Date: 2018-09-27 12:26:01.630440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87ff1e76501f'
down_revision = '31c6eb005764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_result',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('brownfield_site_publication_id', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['brownfield_site_publication_id'],
                                ['brownfield_site_publication.publication'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('brownfield_site_publication', 'validation_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brownfield_site_publication',
                  sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                            nullable=True))

    op.drop_table('validation_result')
    # ### end Alembic commands ###
