"""empty message

Revision ID: 8e6a2d9992c7
Revises: 4bd471ac67bb
Create Date: 2018-09-24 13:54:51.591505

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e6a2d9992c7'
down_revision = '4bd471ac67bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('feature', sa.String(length=256), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('publication', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('feature')
    )
    op.create_table('organisation',
    sa.Column('organisation', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('feature_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.feature'], name='organisation_feature_fkey'),
    sa.PrimaryKeyConstraint('organisation')
    )
    op.add_column('brownfield_site_publication', sa.Column('organisation_id', sa.String(length=64), nullable=True))
    op.create_foreign_key('brownfield_publication_organisation_fkey', 'brownfield_site_publication', 'organisation', ['organisation_id'], ['organisation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brownfield_site_publication', sa.Column('organisation', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint('brownfield_publication_organisation_fkey', 'brownfield_site_publication', type_='foreignkey')
    op.drop_column('brownfield_site_publication', 'organisation_id')
    op.drop_table('organisation')
    op.drop_table('feature')
    # ### end Alembic commands ###
