"""empty message

Revision ID: 9df15334a84c
Revises: 
Create Date: 2018-11-28 11:44:56.791702

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9df15334a84c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brownfield_site_register',
    sa.Column('organisation', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326), nullable=True),
    sa.Column('geojson', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('publication', sa.String(length=64), nullable=True),
    sa.Column('register_url', sa.Text(), nullable=True),
    sa.Column('publication_copyright', sa.String(length=64), nullable=True),
    sa.Column('publication_licence', sa.String(length=64), nullable=True),
    sa.Column('publication_suffix', sa.String(length=64), nullable=True),
    sa.Column('register_geojson', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.Column('validation_result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('organisation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brownfield_site_register')
    # ### end Alembic commands ###
