"""empty message

Revision ID: bc753c720ed5
Revises: 993cc56e2c67
Create Date: 2018-11-28 10:23:46.377034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc753c720ed5'
down_revision = '993cc56e2c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfield_site_register', 'brownfield_register_publication', new_column_name='publication')
    op.alter_column('brownfield_site_register', 'brownfield_register_url', new_column_name='register_url')
    op.alter_column('brownfield_site_register', 'brownfield_register_copyright', new_column_name='publication_copyright')
    op.alter_column('brownfield_site_register', 'brownfield_register_licence', new_column_name='publication_licence')
    op.alter_column('brownfield_site_register', 'brownfield_register_suffix', new_column_name='publication_suffix')
    op.alter_column('brownfield_site_register', 'brownfield_register_geojson', new_column_name='register_geojson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfield_site_register', 'publication', new_column_name='brownfield_register_publication')
    op.alter_column('brownfield_site_register', 'register_url', new_column_name='brownfield_register_url')
    op.alter_column('brownfield_site_register', 'publication_copyright', new_column_name='brownfield_register_copyright')
    op.alter_column('brownfield_site_register', 'publication_licence', new_column_name='brownfield_register_licence')
    op.alter_column('brownfield_site_register', 'publication_suffix', new_column_name='brownfield_register_suffix')
    op.alter_column('brownfield_site_register', 'register_geojson', new_column_name='brownfield_register_geojson')
    # ### end Alembic commands ###
