"""empty message

Revision ID: e2be4d7534ce
Revises: fe9fa5ae8945
Create Date: 2018-11-27 15:54:50.408484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import JSON, JSONB

revision = 'e2be4d7534ce'
down_revision = 'fe9fa5ae8945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='organisation',
        column_name='geojson',
        type_=JSON
    )
    op.alter_column(
        table_name='organisation',
        column_name='brownfield_register_geojson',
        type_=JSON
    )
    op.alter_column(
        table_name='organisation',
        column_name='validation_data',
        type_=JSON
    )
    op.alter_column(
        table_name='organisation',
        column_name='validation_result',
        type_=JSON
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='organisation',
        column_name='geojson',
        type_=JSONB
    )
    op.alter_column(
        table_name='organisation',
        column_name='brownfield_register_geojson',
        type_=JSONB
    )
    op.alter_column(
        table_name='organisation',
        column_name='validation_data',
        type_=JSONB
    )
    op.alter_column(
        table_name='organisation',
        column_name='validation_result',
        type_=JSONB
    )
    # ### end Alembic commands ###
