"""empty message

Revision ID: ebf1aa2d4fb4
Revises: 026ec67033ac
Create Date: 2019-12-04 16:31:17.557895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebf1aa2d4fb4'
down_revision = '026ec67033ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('result_model', 'upload', new_column_name='input')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###')
    op.alter_column('result_model', 'input', new_column_name='upload')
    # ### end Alembic commands ###
