"""empty message

Revision ID: fe9fa5ae8945
Revises: 70a3c7402419
Create Date: 2018-11-27 10:34:29.321521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

from application.models import BrownfieldSiteRegister

revision = 'fe9fa5ae8945'
down_revision = '70a3c7402419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('data_source', sa.Text(), nullable=True))
    op.add_column('organisation', sa.Column('validation_created_date', sa.DateTime(), nullable=True))
    op.add_column('organisation', sa.Column('validation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organisation', sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    session = Session(bind=op.get_bind())
    for org in session.query(BrownfieldSiteRegister).all():
        if org.validation is not None:
            org.validation_result = org.validation.result
            org.data_source = org.validation.data_source
            org.validation_data = org.validation.data
            org.validation_created_date = org.validation.created_date
            session.add(org)
            session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'validation_result')
    op.drop_column('organisation', 'validation_data')
    op.drop_column('organisation', 'validation_created_date')
    op.drop_column('organisation', 'data_source')
    # ### end Alembic commands ###
